# Generated by Django 4.1.3 on 2022-12-20 03:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('display_type', models.PositiveIntegerField(choices=[(1, 'HTML'), (2, 'Newest article'), (3, 'Hottest article'), (4, 'Recent comments')], default=1, verbose_name='Show Type')),
                ('content', models.CharField(blank=True, help_text='If setting type is not HTML, can be blank', max_length=500, verbose_name='Content')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Show'), (0, 'Hide')], default=1, verbose_name='Status')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Sidebar',
                'verbose_name_plural': 'Sidebar',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('herf', models.URLField(verbose_name='Link')),
                ('status', models.PositiveIntegerField(choices=[(1, 'Normal'), (0, 'Delete')], default=1, verbose_name='Status')),
                ('weight', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, help_text='The ones with high weight are shown in the front', verbose_name='Weight')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Friendly Link',
                'verbose_name_plural': 'Friendly Link',
            },
        ),
    ]
